<%@ Page Title="Contact" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeFile="Contact.aspx.vb" Inherits="Contact" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
     
    </hgroup>

    <section class="contact">
        <h2>Khách Hàng</h2>
        <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="Makh" DataSourceID="SqlDataSource3">
            <Fields>
                <asp:BoundField DataField="Makh" HeaderText="Makh" ReadOnly="True" SortExpression="Makh" />
                <asp:BoundField DataField="Ho_va_ten" HeaderText="Ho_va_ten" SortExpression="Ho_va_ten" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            </Fields>
        </asp:DetailsView>
       
     
        
        <asp:SqlDataSource ID="SqlDataSource3" runat="server"></asp:SqlDataSource>
       
     
        
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="Data Source=CONGIT-PC\SQLEXPRESS;Initial Catalog=Nhom5_QuanLyBanHang;Integrated Security=True" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [Makh], [Ho_va_ten], [Email] FROM [Khach_Hang]"></asp:SqlDataSource>
     <h2>Hóa Đơn</h2>
        <asp:DetailsView ID="DetailsView2" runat="server" Height="50px" Width="125px" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="Makh" DataSourceID="SqlDataSource2">
            <Fields>
                <asp:BoundField DataField="Makh" HeaderText="Makh" ReadOnly="True" SortExpression="Makh" />
                <asp:BoundField DataField="So_Hoa_Don" HeaderText="So_Hoa_Don" SortExpression="So_Hoa_Don" />
                <asp:BoundField DataField="id_kh" HeaderText="id_kh" SortExpression="id_kh" />
            </Fields>
        </asp:DetailsView>
        
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="Data Source=CONGIT-PC\SQLEXPRESS;Initial Catalog=Nhom5_QuanLyBanHang;Integrated Security=True" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [Makh], [So_Hoa_Don], [id_kh] FROM [Hoa_Don]"></asp:SqlDataSource>
        
    </section>

    <section class="contact">
        <header>
      
        </header>
        
       
        
    </section>

    <section class="contact">
       
        
    </section>
</asp:Content>